README.md, augur/README.md, augur/deploy.yaml
Deployed: 15maavfe65e3j66safqh6lvfqs.provider2.akashdev.net
I'm getting SSL errors when I tried to navigate to it, so if you also see something like "Your connection is not private" from your browser, choose the "proceed anyway" option and you should be able to access the Augur app.
akash provider lease-status:
{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"15maavfe65e3j66safqh6lvfqs.provider2.akashdev.net"
],
"replicas": 0,
}
},
}
=> ID 5bshce3qiky00p0: Add Augur to DeFi apps

README.md, jira/README.md, jira/deploy.yaml
{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"pesmdc6ik5dqf273i0rjrhcs5g.provider1.akashdev.net"
],
"replicas": 0,
}
},
}
I can verify the link above works, but it gets shut down after a a while, so you may get 404 by the time you see this. If you were to deploy this yourself, note that:
- Jira recommends a lot more resources than I'm specifying in the deploy yml, so once deployed, you're going to see 502 while it sets up.
- For me, after deploying it took around 6 minutes to go from 502 to seeing the Jira page.
- Jira show a progress bar to indicate it's setting up, and it'll take another 10-15 minutes from there.
- After some time, …
=> ID 5bshce3qiky00p0: Add Jira to Project Management

wordpress/deploy.yaml
This was missing configuration for the required database server, which meant that whoever wanted to use this as an example of how to get a "more complex" application running on Akash would be presented with database errors.
=> Update wordpress deployment example

minecraft/deploy.yaml
otherwise it fails with the following error:
web: Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
web:     java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
web: 2022-04-08T14:36:47.969Z    WARN    mc-server-runner    sub-process failed    {"exitCode": 1}
to update the image, the image source needs to be changed:
- https://github.com/slowriot/docker-minecraft-server/blob/master/Dockerfile#L1
it looks like adoptopenjdk:16-jre needs to be replaced with eclipse-temurin:17-jre (its successor) or similar.
=> fix minecraft to v1.17

nodle-node/Dockerfile, nodle-node/deploy.yaml
The `nodle-parachain` binary no longer supports the `main` spec (moved to `nodle-chain`), this PR changes your config to sync the parachain instead of the soon to be deprecated solo chain.
=> default to eden chain spec

README.md, flame/README.md, flame/deploy.yaml
This PR adds a deployment manifest for Flame, a self-hosted startpage / application dashboard.
=> add flame deployment

README.md, uptime-kuma/README.md, uptime-kuma/deploy.yaml
This PR adds a deployment manifest for Uptime-Kuma, a self-hosted monitoring tool like "Uptime Robot".
=> add uptime-kuma deployment

wordpress/README.md
the p in WordPress should be capital! 
https://twitter.com/octalmage/status/1642333485728686084
=> fix: WordPress has a capital P

README.md, yacy/README.md, yacy/deploy.yaml
See: [https://yacy.net](https://yacy.net)
Note: Port 8090 must be exposed as 80 or otherwise YaCy will refuse to crawl.
=> Add YaCy Search Engine Software

torchbench/Akash_Gpu_Benchmark_Notebook.ipynb, torchbench/Dockerfile, torchbench/docker_healthcheck.py, torchbench/fix-permissions, torchbench/initial-condarc, torchbench/jupyter_server_config.py, torchbench/run.sh, torchbench/start-notebook.sh, torchbench/start-singleuser.sh, torchbench/start.sh, torchbench/torchbench_gpu_sdl.yaml
Work in progress PR for adding torchbench gpu benchmarking sdl
=> add torchbench example: WIP 

comfyui/README.md, comfyui/deploy.yaml
- Added cmd arg to disable xformers (doesn't work with it enabled for some reason - still need to root cause)
- Added reference in README on how to load checkpoints, VAEs and upscalers
=> Fix: disable xformers, add comfyui reference

.gitignore, ssh-bare-images/Dockerfile.ubuntu, ssh-bare-images/ssh-entrypoint.sh
This task adds an ubuntu image to be used as a bare VM image with ssh access as described in akash-network/cloudmos#227
Once this is approved I'll build it, push to github registry and proceed with UI works within cloudmos. After that I plan to add other distros.
=> Add ubuntu bare image with ssh

Llama-3.1/Llama-3.1-405B-Instruct-AWQ-INT4.yml, Llama-3.1/Llama-3.1-405B-Instruct-FP8.yaml, Llama-3.1/Llama-3.1-405B-Instruct.yaml, Llama-3.1/Llama-3.1-8B-Instruct.yaml, Llama-3/Llama-3-70B-Instruct.yaml, Llama-3/Llama-3-8B-Instruct.yaml
the reason being are different issues ranging from "CUDA error: uncorrectable ECC error encountered" up to "NCCL error: unhandled system error" sort of errors with seemingly the same vllm/vllm-openai:v0.5.3.post1 image until it turned out that they pushed different versions of it behind the same image tag v0.5.3.post1
Example:
- BAD vllm/vllm-openai@sha256:f69e0acef342b7d0475086a5a99afa9e2ba2ee74c5ace91052dd3680b354ac4c (CUDA: 12.4.1)
- GOOD vllm/vllm-openai@sha256:bfb0403010061e61b692e337945fb9694baefb03b0725d62adab9cca6139ea62 (CUDA: 12.1.0)
=> fix(image/llama): use the exact digest manifest

README.md, dria/README.md, dria/deploy.yaml
This PR adds recentrly launched [Dria](dria.co) Knowlesge Network compute node to the Awesome Akash repo. It allows deployers to join the network and execute assign tasks. 
There will be GPU support additions in the future
=> dria: add DKN compute node

base-ssh/Dockerfile.centos, base-ssh/Dockerfile.debian, base-ssh/Dockerfile.suse, base-ssh/Dockerfile.ubuntu, ssh-ubuntu/Dockerfile.ubuntu
Use the default distro package manager to install `tini` whenever possible. If the package manager is unavailable or does not provide `tini`, ensure the GPG signature is verified using a trusted side-channel method.
Changes:
- Updated Dockerfiles for CentOS, Debian, SUSE, and Ubuntu to install `tini` via the package manager or, if necessary, from the official release with GPG verification.
- Adjusted entry points to utilize the package-installed `tini`.
=> security(base-ssh, ssh-ubuntu): use distro package manager to install tini

ipfs/README.md, ipfs/deploy.yaml
I noticed the IPFS node is extremely outdated - and does not actually work. This PR updates to lates IPFS Kubo version + adds basic auth for webui and API to actually make it useful and usable.
* Udpate to `ipfs/kubo:v0.30.0`
* Add script to fix CSRF issues
* Add `nginx` service
* Add basic auth for IPFS UI and API (configurable via env vars)
ISSUES:
* Publishing to IPNS fails with gateway timeout
* Uploading larger files fails with `Payload too large` error
I added nginx config to fix these, but it does not seem to affect, would appreciate help with fixing these:)
=> ipfs: update, add auth

dria/README.md, dria/deploy.yaml
This PR updates 
* DKN node to v0.2.2
* Llama to latest `latest` (`a45c1ae866f0ad115b5b2b5048cb80e02a8c49c36f60d49f449b0d6a3825cdbf`)
* Update resource requirements
* Add a note about potential netowrking issues with some providers (known to Dria - https://github.com/firstbatchxyz/dkn-compute-node/issues/119)
=> dria: update to v0.2.2

.github/workflows/main.yaml, automatic-deployment-CICD-template/deploy.yaml, automatic-deployment-CICD-template/javascript/main.bats
The previous PR initialized github actions but a workflow was failing due to capital repo name. That has been fixed.
=> fix github actions

.github/workflows/main.yaml, automatic-deployment-CICD-template/deploy.yaml
the previous PR had a small typo in organization name. This PR fixes it and now all github action workflows should run perfectly.
=> fix organization name in github action

bitcoin-knots-mempool-ui/README.md, bitcoin-knots-mempool-ui/deploy-mempool.yaml
Updated README and deploy-mempool.yaml to clarify that `mempool/electrs` is a fork of electrs, not Esplora. This fixes misleading references and improves accuracy for users setting up address lookup services.
=> fix: correct description of mempool/electrs as electrs fork, not Esplora

bitcoin-knots-mempool-ui/README.md
- Renamed "Blockstream/electrs" to "Blockstream/esplora" in README for clarity
=> Clarify backend table labels

bitcoin-knots-mempool-ui/README.md, bitcoin-knots-mempool-ui/deploy-mempool.yaml, bitcoin-knots-mempool-ui/deploy.yaml
- Updated README.md with a new section on using leased static public IPs to enable inbound Bitcoin P2P connections (port 8333)
- Noted fallback to random NodePort behavior and JSON-RPC ingress unaffected
- Documented current Akash limitation: leased IPs are not exposed via env vars
(see https://github.com/akash-network/support/issues/284)
- Suggested workaround using `curl ifconfig.me` to obtain public IP at runtime
- Added SDL comments in `deploy.yaml` and `deploy-mempool.yaml`:
- Documented how to enable `ip: bitcoind` under `expose`
- Kept IP leasing commented out by default due to limited provider support
=> bitcoind: add IP leasing support and guidance for inbound P2P connectivity
