README.md

Signed-off-by: Greg Osuri <me@gregosuri.com>

Add Serum DEX UI to DeFi

---

tetris/README.md
tetris/deploy.yaml

It was a great experience with your product guys <3 sky is the limit and above.

Tetris Game on Awesome Akash

---

README.md
ghost/README.md
ghost/deploy.yml

{
"services": {
"ghost": {
"name": "ghost",
"total": 1,
"uris": [
"538dqfcf7tdjtbp250vlepvi5k.provider4.akashdev.net"
],
"replicas": 0,
}
},
}

ID oprpishvoz1e1w: Add Ghost to blogging apps

---

README.md
pacman/README.md
pacman/deploy.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"2jvq1e9o75eqp5g2a1rletmhc0.provider2.akashdev.net"
],
"replicas": 0,
}
},
}

ID 7ettq2chho2i5la: Add Pac-Man game

---

README.md
jenkins/README.md
jenkins/deploy.yaml

{
"services": {
"jenkins": {
"name": "jenkins",
"total": 1,
"uris": [
"kb72a0eqedfjh3vo3noff2loa0.provider4.akashdev.net"
],
"replicas": 0,
}
},
"forwarded-ports": {
"jenkins": [
{
"port": 50000,
"externalPort": 30556,
"proto": "TCP",
"name": "jenkins"
}
]
}
}

ID g9qjfxwljdyyyd6: Add Jenkins to Continuous Integration

---

README.md
pancake-swap/README.md
pancake-swap/deploy.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"8rn182r6ltctr4b3mgc73mdtqs.provider3.akashdev.net"
],
"replicas": 0,
}
},
}

ID 7ettq2chho2i5la: Add Pancake Swap to DeFi apps

---

README.md
steemcn/README.md
steemcn/deploy.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"gavh3uoilpf4n3qigbkoa4pc90.provider3.akashdev.net"
],
"replicas": 0,
}
},
}

ID dddzdxlvw0fsrv9: Added steemCN to Blogging apps

---

README.md
sushiswap/README.md
sushiswap/deploy.yml

```
{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"4urnh6k1dtfjbackj7584b68d4.provider2.akashdev.net"
],
"replicas": 0,
}
},
}
```

ID 2otlcj2ud2dazoo: Add SushiSwap to DeFi apps

---

README.md
luaswap/README.md
luaswap/deploy-luaswap.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"9v0u3fl1rpdavas7puvfsn2nbg.provider3.akashdev.net"
],
"replicas": 0,
}
},
}

ID e5izjk6jorm2l9z: Add Luaswap

---

README.md
caddy/README.md
caddy/deploy.yml
mongoDB/README.md
mongoDB/deploy.yml
pgadmin4/README.md
pgadmin4/deploy.yml
supermario/README.md
supermario/deploy.yml
uniswap/81ow3i7lnhnivs9.json

Deployed Uniswap app, ID: 81ow3i7lnhnivs9
http://mt60bmuka993hbirvq0fis7ubk.provider4.akashdev.net/#/swap
{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"mt60bmuka993hbirvq0fis7ubk.provider4.akashdev.net"
],
"replicas": 0,
}
},
}

Deployed Uniswap, Pacman, Added and deployed Supermario, pgAdmin4, MongoDB, Caddy WebServer app, ID: 81ow3i7lnhnivs9

---

README.md
dego-stats/README.md
dego-stats/deploy.yml

Site: http://pfbnv7endta7d2jk3r83uioeno.provider5.akashdev.net/
{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"pfbnv7endta7d2jk3r83uioeno.provider5.akashdev.net"
],
"replicas": 0,
}
},
}

ID 32azo0ztv9d7s40: Add DEGO Stats to Tools

---

README.md
bancor/README.md
bancor/deploy.yml

```
{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"4ge79u689dd3d2qie2670bbjhg.provider5.akashdev.net"
],
"replicas": 0,
}
},
}
```

ID 697fapis87f8myw: Add Bancor to DeFi apps

---

MyEtherWallet/README.md
MyEtherWallet/deploy.yml
README.md

ID: 7osljvkpwzp0nu0 Add MyEtherWallet to Wallet
links: d37ipnkmlpea90bs95to5time0.provider2.akashdev.net

ID: 7osljvkpwzp0nu0 Add MyEtherWallet to Wallet

---

README.md
postgres/README.md
postgres/deploy_postgres.yml

Lease-status:
{
"services": {
"postgres": {
"name": "postgres",
"total": 1,
"uris": null,
"replicas": 0,
}
},
"forwarded-ports": {
"postgres": [
{
"port": 5432,
"externalPort": 32674,
"proto": "TCP",
"name": "postgres"
}
]
}
}

App: PostgreSQL ID: 81ow3i7lnhnivs9

---

Dharani/README.md
Dharani/dharani.yaml
README.md

```json= {
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"dcloud.dharani.multiverse.tk",
"sl349q2fc9d3hesekg0c3cp9rk.provider2.akashdev.net"
],
"replicas": 0,
}
},
}
```

ID ek6kts3ye4rea5u: Adding Dharani to Built with Cosmos-SDK tag

---

README.md
tetris2/README.md
tetris2/deploy.yaml

{
"services": {
"tetris": {
"name": "tetris",
"total": 1,
"uris": [
"1rpht05r91el31ia7bnb88u7rs.provider2.akashdev.net"
],
"replicas": 0,
}
},
}

ID d12slsjx3mdhw17: Add Tetris2 to game apps

---

README.md
mintr/README.md
mintr/deploy-mintr.yml

Synthetix Mintr dApp
{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"ohi6utv5ph8gb0r37ganuta1is.provider5.akashdev.net"
],
"replicas": 0,
}
},
}

ID 8f6afwus2hgd1n1 : Mintr

---

README.md
balancer/README.md
balancer/deploy.yml

```
{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"g73mq8edi5a8jadia1aidhocgo.provider2.akashdev.net"
],
"replicas": 0,
}
},
}
```

ID bf1h269owj8j7uh: Add Balancer to DeFi apps

---

README.md
tronwallet/README.md
tronwallet/deploy.yml

akash provider lease-status:
{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"69psvqo6npcjt8c056d44omnlo.provider2.akashdev.net"
],
"replicas": 0,
}
},
}

ID: 7619g4vil7v5v5e verify tronwallet

---

README.md
microbox/README.md
microbox/deploy.yml

{
"services": {
"redis": {
"name": "redis",
"total": 1,
"uris": null,
"replicas": 0,
},
"web": {
"name": "web",
"total": 1,
"uris": [
"n7h4sv9ndte0v0h8qkpp5d4oqs.provider3.akashdev.net"
],
"replicas": 0,
}
},
}

 ID: 4wjrrrz2vgao522 verify microbox.

---

README.md
authsteem/README.md
authsteem/deploy.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"hvpa9jm5rdc8n427udu5ftd95g.provider5.akashdev.net"
],
"replicas": 0,
}
},
}

ID: bw1hutrojts1iez verify authsteem

---

README.md
wordpress/README.md
wordpress/deploy.yml

{
"services": {
"wordpress": {
"name": "wordpress",
"total": 1,
"uris": [
"8mmlsctkfpca97kkqbjciafnqo.provider5.akashdev.net"
],
"replicas": 0,
}
},
}

ID dinx75udn35081o: Add Wordpress to Blogging apps

---

README.md
snake-game/README.md
snake-game/deploy.yml

{
"lease_id": {
"owner": "akash1gx3mz5f6484av9src3drh096e7emgfjn7dt9r8",
"dseq": "159108",
"gseq": 1,
"oseq": 1,
"provider": "akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl"
},
"state": "active",
"price": {
"denom": "uakt",
"amount": "7174"
}
}

ID btp2u6rihl2h18b: Add snake-game to gaming apps

---

README.md
Thorchain-BEPSwap/README.md
Thorchain-BEPSwap/thorchain.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"300cl9s3ulbph244b6qqp6dkm0.provider3.akashdev.net"
],
"replicas": 0,
}
},
}

ID fs5ear1csdswwej: Add ThorChain BEPSwap to DeFi apps

---

README.md
Yearn.finance/README.md
Yearn.finance/deploy-yearn.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"8s72s6tabpce3acsbd4ihe6g5o.provider4.akashdev.net"
],
"replicas": 0,
}
},
}

ID:1w3hg0t5tybalkp Deploy Yearn.finance on Akash

---

README.md
uma-protocol/README.md
uma-protocol/deploy.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"lv7lj64h55a6rafogor0nvvr3c.provider4.akashdev.net"
],
"replicas": 0,
}
},
}

ID 7ettq2chho2i5la: Add Uma Protocol to DeFi apps

---

README.md
curve/README.md
curve/deploy.yml

{
"services": {
"curve": {
"name": "curve",
"total": 1,
"uris": [
"eq6s5u93shfk189dr7iakcsmus.provider5.akashdev.net"
],
"replicas": 0,
}
},
}

ID 81ow3i7lnhnivs9: Add Curve UI app

---

README.md
adminer/README.md
adminer/deploy.yaml

{
"services": {
"adminer": {
"name": "adminer",
"total": 1,
"uris": [
"g7r3e4k11pf997nc9jcbi6bcqo.provider5.akashdev.net"
],
"replicas": 0,
}
},
}

ID ffu8351zo0royir: Add Adminer to Databases and Administration apps

---

README.md
synthetix.exchange/README.md
synthetix.exchange/deploy.yml

http://b6h664cqt5c5t67ppiesdrkiog.provider3.akashdev.net/
`{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"b6h664cqt5c5t67ppiesdrkiog.provider3.akashdev.net"
],
"replicas": 0,
}
},
}`

ID avp156ysiljvbjr: Add Synthetix.Exchange to DeFi apps

---

MySQL/README.md
MySQL/deploy.yml
README.md

lease-status
{
"services": {
"mysql": {
"name": "mysql",
"total": 1,
"uris": [
"t9jqckqcflcu95j8i8t23lbkr4.provider1.akashdev.net"
],
"replicas": 0,
}
},
"forwarded-ports": {
"mysql": [
{
"port": 3306,
"externalPort": 31716,
"proto": "TCP",
"name": "mysql"
}
]
}
}

App MySQL, ID: 81ow3i7lnhnivs9

---

README.md
confluence/README.md
confluence/deploy.yaml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"mm9164dochd67bkrqfade00ufc.provider3.akashdev.net"
],
"replicas": 0,
}
},
}

ID 5bshce3qiky00p0: Add Confluence Server to Blogging

---

README.md
bitbucket/README.md
bitbucket/deploy.yaml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"b89uu8t6cpej9f8utuvto1eri4.provider2.akashdev.net"
],
"replicas": 0,
}
},
}

ID 5bshce3qiky00p0: Add Bitbucket Server to Continuous Integration

---

README.md
renprotocol/README.md
renprotocol/deploy.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"c5fh0i0ietclnc6ush378isr5s.provider2.akashdev.net"
],
"replicas": 0,
}
},
}

ID fpszuvlusqdyia2: Add Ren Protocol to DeFi apps

---

README.md
freeflix-nucleus/README.md
freeflix-nucleus/deploy.yml

http://dcloud.nucleus.freeflix.live/
{
"lease_id": {
"owner": "akash1w9k2cdhtr0e9ctyafd0fqdlms5q709hzfxwcxw",
"dseq": "183639",
"gseq": 1,
"oseq": 1,
"provider": "akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl"
},
"state": "active",
"price": {
"denom": "uakt",
"amount": "85"
}
}

ID b68w7r8c6i67v4c: Add FreeFlix Nucleus to Media apps

---

README.md
owncloud/4nr7g1tx3m95mvz.json
owncloud/README.md
owncloud/owncloud.yml

{
"services": {
"owncloud": {
"name": "owncloud",
"total": 1,
"uris": [
"eug3adjnllaop39fj720goabfg.provider4.akashdev.net"
],
"replicas": 0,
}
},
}

ID 4nr7g1tx3m95mvz : Add Owncloud to Tools apps

---

README.md
serum/GUIDE.md
serum/README.md
serum/deploy.yaml

Signed-off-by: Greg Osuri <me@gregosuri.com>

add serum dex ui

---

README.md
drupal/README.md
drupal/deploy.yml

{
"services": {
"drupal": {
"name": "drupal",
"total": 1,
"uris": [
"el2nu8mi2t8jnf4ahiv5gce4m0.provider2.akashdev.net"
],
"replicas": 0,
}
},
}

ID ai7mw4cssh0a27k: Add Drupal to Blogging apps

---

README.md
couchdb/README.md
couchdb/deploy.yml

{
"services": {
"couchdb": {
"name": "couchdb",
"total": 1,
"uris": [
"p92muhte35eolcuk11qv0he5ck.provider5.akashdev.net"
],
"replicas": 0,
}
},
}

ID 67g42ha79da8pji: Add CouchDB to Databases and Administration apps

---

README.md
quill-editor/README.md
quill-editor/deploy.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"b8b32h9hepb8hbttstv2o1jvik.provider2.akashdev.net"
],
"replicas": 0,
}
},
}

ID: 4sg1hzton5xb27q add quill-editor

---

README.md
mattermost/README.md
mattermost/deploy.yaml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"9d4dd6u89ddavac0f8k5agtq94.provider3.akashdev.net"
],
"replicas": 0,
}
},
}

ID 5bshce3qiky00p0: Add Mattermost to Chat

---

README.md
yfii/README.md
yfii/deploy.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"c7gt9rvp85bfh49u8r896h12bk.provider3.akashdev.net"
],
"replicas": 0,
}
},
}

ID 2otlcj2ud2dazoo: Add YFII to DeFi apps

---

README.md
wikijs/README.md
wikijs/deploy.yaml

{
"services": {
"wiki": {
"name": "wiki",
"total": 1,
"uris": [
"s1sogbrlotas311g354d4qobf0.provider4.akashdev.net"
],
"replicas": 0,
}
},
}

ID 5bshce3qiky00p0: Add WikiJS to Blogging

---

README.md
dart/README.md
dart/dart.yml

{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"11mopgotu9fnhclq14a5kksloo.provider3.akashdev.net"
],
"replicas": 0,
}
},
}

ID:34neo4ggwc1nrds add dart-hello

---

README.md
redmine/README.md
redmine/deploy.yml

Login to access: admin
Password: 12345
{
"services": {
"db": {
"name": "db",
"total": 1,
"uris": null,
"replicas": 0,
},
"redmine": {
"name": "redmine",
"total": 1,
"uris": [
"iq1ljrbqmlf3951j7ci4gq9ev4.provider4.akashdev.net"
],
"replicas": 0,
}
},
}

ID 7ettq2chho2i5la: Add Redmine

---

README.md
ufo-data-vis/README.md
ufo-data-vis/deploy.yaml

I decided to try to deploy a data visualization project I worked on some time ago on Akash. It works! I added a new category "Data Visualization".
{
"services": {
"web": {
"name": "web",
"total": 1,
"uris": [
"oprhriqmvp9hp5t5odq1q67m9g.provider2.akashdev.net"
],
"replicas": 0,
}
},
}

ID 5bshce3qiky00p0: Add UFO Sightings to Data Visualization

---

big-dipper/deploy.yaml

Temporarily reduce storage requirements.

fix(big-dipper): reduce storage

---

onetimepad/README.md
onetimepad/deploy.yml

Onetimepad: A decentralised app deployed on the akash mainnet.

onetimepad

---

README.md

small tweaks

---

README.md
matomo/README.md
matomo/deploy.yml

Matomo is a self hosted and open source alternative to google analytics

Add matomo

---

README.md
ipfs/README.md
ipfs/deploy.yml
zammad/README.md
zammad/deploy.yml

zammad is a open source ticketing/helpdesk tool
IPFS is a peer-to-peer protocol for file storing (simplified)

add ipfs & zammad

---

README.md
discourse/README.md
discourse/deploy.yml
odoo/deploy.yml

**Project name:** Discourse on Akash
**List of members:** Just me
**A description of your project:** 
This guide and fully functional SDL is intended to describe the process to run Discourse Multi-Tiered application on Akash Network.
The SDL deploy a Multi-Tiered application with 4 services/containers:
- PostgreSQL
- Redis
- Sidekiq discourse
- Discourse
**Demo deployment video using Akashlytics:**
[![Discourse on Akash Network](https://img.youtube.com/vi/XFweRMMZ10s/0.jpg)](https://youtu.be/XFweRMMZ10s)

Discourse on Akash: Working SDL and deployment guide

---

README.md
sifchain-ui/Dockerfile
sifchain-ui/Makefile
sifchain-ui/README.md
sifchain-ui/default.conf
sifchain-ui/deploy.yaml
sifchain-ui/setenv

Currently deployed at https://d3akash.cloud:31832 :-)
Have to accept a self-signed certificate.

add Sifchain DEX

---

README.md

Fixes spelling error in README.

"business" mispelled in README, showing in Akashlytics

---

sifchain-ui/Dockerfile
sifchain-ui/Makefile
sifchain-ui/deploy.yaml

Currently deployed here https://sifchain.akash.pro

bump sifchain-ui dex

---

README.md
disk-speed-test/Dockerfile
disk-speed-test/run.sh
fast/README.md
fast/deploy.yaml
geekbench/Dockerfile
geekbench/README.md
geekbench/deploy.yaml
geekbench/entrypoint.sh
librespeed/README.md
librespeed/deploy.yaml
open-speed-test/README.md
open-speed-test/deploy.yaml
speedtest-cli/Dockerfile
speedtest-cli/deploy.yaml
speedtest-cli/run.sh
speedtest-tracker/README.md
speedtest-tracker/deploy.yaml

- [Speedtest by Ookla](speedtest-cli)
- [Fast.com by Netflix](fast)
- [Geekbench 5](geekbench)
- [Speedtest Tracker](speedtest-tracker)
- [Librespeed](librespeed)
- [OpenSpeedTest](openspeedtest)

Akash provider benchmarking suite

---

README.md
hashicorp-vault/README.md
hashicorp-vault/deploy.yaml

Image : https://hub.docker.com/_/vault
Tested and works fine

Hashicorp Vault server on Akash Cloud

---

redis/README.md
redis/deploy.yaml

Tested and working using the following command *(exposed port 80)*
redis-cli -u redis://rootpassword@\<provider\>:\<port\>

Standalone Redis Deployment 

---

ghost/deploy.yaml

Updated to the latest major version of Ghost.

Ghost Update

---

ghost/README.md
ghost/deploy-mysql.yaml
ghost/deploy.yaml

Supersedes:
- https://github.com/ovrclk/awesome-akash/pull/316
- https://github.com/ovrclk/awesome-akash/pull/315

update ghost to v5.12 and add mysql + pers.storage example

---

README.md
json-server/README.md
json-server/deploy.yaml

Add support for https://github.com/typicode/json-server

json-server

---

README.md
monero-pool/Dockerfile-for-Akash
monero-pool/README.md
monero-pool/deploy.yaml
monero-pool/run.sh
monero-pool/start.sh

Add support for [monero-pool](https://github.com/jtgrassie/monero-pool)

monero-pool by jtgrassie

---

README.md
budibase/README.md
budibase/deploy.yaml

This PR adds Budibase - a low code platform for creating internal apps, workflows, and admin panels in minutes. Supports PostgreSQL, MySQL, MSSQL, MongoDB, Rest API, Docker, K8s, and more.
See https://github.com/Budibase/budibase for more info.

Add Budibase deployment

---

wordpress/README.md
wordpress/deploy.yaml

Replaces current Wordpress SDL with stable version including Redis and MariaDB

replace wordpress sdl with stable manifest

---

README.md
csgo/README.md
csgo/csgo.yaml
csgo/deploy.yaml
holdfastnaw/README.md
holdfastnaw/deploy.yaml
holdfastnaw/holdfastnaw.yaml
mordhau/README.md
mordhau/deploy.yaml
mordhau/mordhau.yaml
squad/README.md
squad/deploy.yaml
squad/squad.yaml
steamcmd/steamcmd.yaml
steampipe/README.md
steampipe/deploy.yaml
steampipe/steampipe.yaml
tf2/README.md
tf2/deploy.yaml
tf2/tf2.yaml
valheim/README.md
valheim/deploy.yaml
valheim/valheim.yaml

- Counter-Strike: Global Offensive
- Holdfast: Nations At War
- Mordhau
- Squad
- SteamCMD
- SteamPipe
- Team Fortress 2

cm2network game servers

---

README.md
keycloak-iam/README.md
keycloak-iam/deploy.yaml

Keycloak is one of the best open source  IAM tool in the market.

Added keycloak IAM to Akash

---

README.md
tensorflow-jupyter-mnist/README.md
tensorflow-jupyter-mnist/deploy.yaml
tensorflow-serving-mnist/README.md
tensorflow-serving-mnist/deploy.yaml
tensorflow-webapp-mnist/README.md
tensorflow-webapp-mnist/deploy.yaml

Original PR https://github.com/akash-network/awesome-akash/pull/167

ID 5bshce3qiky00p0: Add 3 deployments to Machine Learning

---

README.md

- Update Pocket Link
- Add a ToC
- Remove duplicate headings

Upate main README

---

README.md
waku/README.md
waku/deployment.full.pg.yaml
waku/deployment.minimal.yaml

Adding [Waku](https://waku.org) node deployment into the repo
Kudos to Akash core team (@andy108369) and @shimpa1 for the help with development!
I have 2 waku nodes running on Akash at the moment:
http://waku.myrandomdemos.online:8003/metrics
http://waku-pg.myrandomdemos.online:8003/metrics

chore: add Waku deployments

---

Llama-2-70B/Dockerfile
Llama-2-70B/README.md
Llama-2-70B/deploy.yaml
Llama-2-70B/main.py
Llama-2-70B/static/script.js
Llama-2-70B/static/style.css
Llama-2-70B/templates/index.html
README.md

This deployment was created as part of this Twitter event from Greg: https://twitter.com/gregosuri/status/1681431682379919361?s=20

Add Llama-2 70B

---

AI-Image-App/deploy.yaml
AUTOMATIC1111/deploy.yaml
FastChat/deploy.yaml
Llama-2-70B/deploy.yaml
StableStudio/deploy.yaml
TTS/deploy.yaml
XLM-RoBERTa/deploy.yaml
bert-sentiment-analysis/deploy.yaml
bert/deploy.yaml
dolly-v2-12b/deploy.yaml
flan-t5-xxl/deploy.yaml
gpt-neo/deploy.yaml
redpajama-incite-7b-instruct/deploy.yaml
serge-gpu/deploy.yaml
stable-diffusion-ui/deploy.yaml
stable-diffusion-webui/deploy.yaml
text-generation-webui/deploy.yaml

This PR reformats a few AI sdls and adds the missing gpu vendor attributes to the AUTOMATIC1111 sdl

Reformat of AI sdls and add gpu attribute

---

wordpress/deploy.yaml

feat(wordpress): increase upload_max_filesize,post_max_size,max_execution_time,max_input_time

---

AUTOMATIC1111/README.md
README.md
comfyui/Dockerfile
comfyui/README.md
comfyui/deploy.yaml
comfyui/entrypoint.sh

This PR adds support for ComfyUI on Akash Network

Add comfyui

---

comfyui/Dockerfile
comfyui/deploy.yaml

This update adds xformers support to comfyui and shell history. It also fixes a compatibility issue with the used torch and xformers version. 
Previous PR #455

Update comfyui sdl - enable xformers, shell history

---

comfyui/Dockerfile
comfyui/deploy.yaml
comfyui/entrypoint.sh

This PR adds support for ComfyUI Manager.

Add support for ComfyUI Manager

---

text-generation-webui/Dockerfile
text-generation-webui/README.md
text-generation-webui/deploy.yaml

This PR updates the text-generation-webui to v1.7, the Dockerfile and adds instructions on how to build the docker image

Update text-generation-webui to latest version

---

waku/deployment.full.pg.yaml
waku/deployment.minimal.yaml

We regenerated the enrtree DNS records and need to use the new ones.
@vpavlin, @andy108369, @shimpa1, can you please have a look at this small PR?

update wakuv2 fleet DNS discovery enrtree

---

README.md

Added hyperlink to new Ray deployment folder under the Machine Learning section

update: Add Ray to README under ML

---

README.md
tor-proxy/README.md
tor-proxy/deploy.yaml

I tested this proxy in Akash network and works great  
[Proxy available at ](http://provider.akash.virtualhosting.hk:30753)

Tor proxy that can be deployed into Akash

---

README.md
radicle/README.md
radicle/deploy.yaml

This adds Radicle Seed node deployment 
It is quite basic and I will probably add a few more features controled via env vars, but it seems to work, so I'd like to get some feedback and ideas

feat: add Radicle seed deployment

---

FLock/README.md
FLock/deploy.yml
README.md

FLock template

---

waku/deploy.sqlite.yaml
waku/deploy.yaml

chore(waku): update to v0.28.0, remove signedBy

---

Falcon-7B/Dockerfile
Falcon-7B/deploy.yml
Falcon-7B/falcon7b.py

```
-RUN apt update && apt install -y \
+RUN apt update && apt install -y --no-install-recommends \
python3 \
python3-pip \
-    python3-venv \
-    build-essential \
-    cmake \
-    libopenblas-dev \
-    libomp-dev
+    python3-venv
```

Falcon-7B: bump torch, xformers to support sm_90 capability (for H100)

---

FLock-training-node/README.md
FLock-training-node/deploy.yml
FLock-validator/README.md
FLock-validator/deploy.yml

Flock validator trainer image upgrade. modify some description.

Flock validator trainer image upgrade

---

vLLM/llama3-1-405b-8bit.yaml
vLLM/llama3-70b.yaml

This PR adds a SDL to deploy the Meta-Llama 3.1 405B 8-bit Model on Akash Network

Add Meta-Llama 3.1 405B 8-bit SDL

---

README.md
witnesschain-watchtower/README.md
witnesschain-watchtower/deploy.yml

- Add Witness Chain Watchtower deployment template

Witnesschain watchtower template

---

radicle/config.json
radicle/deploy.yaml

* Update Radicle to 1.1.0
* Update Radicle HTTPD to 0.18.0
* Update base image to latest RH ubi9
* Add logo

chore(radicle): update to 1.1.0, update base image
